2024-05-11 12:32:48,332 INFO    MainThread:264265 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_setup.py:_flush():76] Configure stats pid to 264265
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_setup.py:_flush():76] Loading settings from /home/tzikos/.config/wandb/settings
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_setup.py:_flush():76] Loading settings from /home/tzikos/Desktop/KULeuvenThesis/wandb/settings
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/tzikos/Desktop/KULeuvenThesis/main.py', 'program': '/home/tzikos/Desktop/KULeuvenThesis/main.py'}
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_init.py:_log_setup():526] Logging user logs to /home/tzikos/Desktop/KULeuvenThesis/wandb/run-20240511_123248-64s5zeov/logs/debug.log
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_init.py:_log_setup():527] Logging internal logs to /home/tzikos/Desktop/KULeuvenThesis/wandb/run-20240511_123248-64s5zeov/logs/debug-internal.log
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_init.py:init():566] calling init triggers
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 1e-06, 'batch_size': 64, 'L1': None, 'L2': None, 'A': 1, 'early_patience': 12, 'reduce_lr_patience': 5, 'architecture': 'ECGCNNClassifier', 'experiment': 'tachy', 'use_pretrained': False}
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_init.py:init():616] starting backend
2024-05-11 12:32:48,333 INFO    MainThread:264265 [wandb_init.py:init():620] setting up manager
2024-05-11 12:32:48,335 INFO    MainThread:264265 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-11 12:32:48,339 INFO    MainThread:264265 [wandb_init.py:init():628] backend started and connected
2024-05-11 12:32:48,343 INFO    MainThread:264265 [wandb_init.py:init():720] updated telemetry
2024-05-11 12:32:48,350 INFO    MainThread:264265 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-05-11 12:32:48,395 WARNING MainThread:264265 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-05-11 12:32:52,297 WARNING MsgRouterThr:264265 [router.py:message_loop():77] message_loop has been closed
